name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        pip install setuptools wheel --upgrade
    - name: Lint
      run: |
        flake8 hmmer_reader
        black --check hmmer_reader
        isort --recursive --check-only hmmer_reader
    - name: Test with pytest
      run: |
        pip install pytest --upgrade
        python setup.py test
    - name: Install it
      run: |
        pip install .
    - name: Test installation
      run: |
        pushd ~/
        python -c "import sys; import hmmer_reader; sys.exit(hmmer_reader.test())"
        popd
    - name: Build source distribution
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
